[build]
  base = "juice-shop/frontend"
  command = "npm install && npm run build"
  publish = "dist/frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
